version: '2'

services:
    db:
        image: mysql
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: apitest
            MYSQL_USER: apiuser
            MYSQL_PASSWORD: apipass
        ports:
            - 3306:3306
        volumes:
            - ./sqldump/db.sql:/docker-entrypoint-initdb.d/db.sql
    php:
        build:
            context: php741-fpm
            args:
                TIMEZONE: Europe/Minsk
        volumes:
            - ./restapi:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
        working_dir: /var/www/symfony
    nginx:
        build: nginx
        ports:
            - 80:80
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        links:
            - db